production:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: {{ deploy_app_name }}_production
  username: {{ deploy_app_name }}
  password: {{ mysql_app_db_password }}
  host: localhost
