- name: Install MySQL Server and others packages
  apt: 
   name: "{{ packages }}"
   state: latest
   update_cache: yes
   force_apt_get: yes
  vars:
   packages: ['mysql-server','mysql-client','libmysqlclient-dev','gnupg2']

- name: Install Python ands libs
  apt:
   name: "{{ packages }}"
   state: latest
   update_cache: yes
   force_apt_get: yes
  vars:
   packages: ['python3-mysqldb','python-mysqldb']

- name: Ensure MySQL service is up
  service: name=mysql state=started

- name: copy .my.cnf file with root password credentials
  template:
   src=my.cnf
   dest=/root/.my.cnf
   owner=root
   mode=0600

- name: Update MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_password }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
   - $inventory_hostname
   - $ansible_hostname
   - localhost

- name: Create database user {{ deploy_app_name }}
  mysql_user:
   name: "{{ deploy_app_name }}"
   password: "{{ mysql_app_db_password }}"
   priv: '*.*:ALL'
   state: present

- name: Install NodeJS, nginx...
  apt: name={{ packages }} state=latest update_cache=yes force_apt_get=yes
  vars:
   packages: ['nodejs','nginx','software-properties-common','build-essential']

- name: Remove useless packages from the cache
  apt:
   autoclean: yes
   force_apt_get: yes

- name: Remove dependencies that are no longer required
  apt:
   autoremove: yes
   force_apt_get: yes 
